# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: movie_recommendations.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bmovie_recommendations.proto\"d\n\x1aMovieRecommendationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12 \n\x08\x63\x61tegory\x18\x02 \x01(\x0e\x32\x0e.MovieCategory\x12\x13\n\x0bmax_results\x18\x03 \x01(\x05\"0\n\x13MovieRecommendation\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\"L\n\x1bMovieRecommendationResponse\x12-\n\x0frecommendations\x18\x01 \x03(\x0b\x32\x14.MovieRecommendation*@\n\rMovieCategory\x12\x0b\n\x07MYSTERY\x10\x00\x12\x13\n\x0fSCIENCE_FICTION\x10\x01\x12\r\n\tSELF_HELP\x10\x02\x32Y\n\x0fRecommendations\x12\x46\n\tRecommend\x12\x1b.MovieRecommendationRequest\x1a\x1c.MovieRecommendationResponseb\x06proto3')

_MOVIECATEGORY = DESCRIPTOR.enum_types_by_name['MovieCategory']
MovieCategory = enum_type_wrapper.EnumTypeWrapper(_MOVIECATEGORY)
MYSTERY = 0
SCIENCE_FICTION = 1
SELF_HELP = 2


_MOVIERECOMMENDATIONREQUEST = DESCRIPTOR.message_types_by_name['MovieRecommendationRequest']
_MOVIERECOMMENDATION = DESCRIPTOR.message_types_by_name['MovieRecommendation']
_MOVIERECOMMENDATIONRESPONSE = DESCRIPTOR.message_types_by_name['MovieRecommendationResponse']
MovieRecommendationRequest = _reflection.GeneratedProtocolMessageType('MovieRecommendationRequest', (_message.Message,), {
  'DESCRIPTOR' : _MOVIERECOMMENDATIONREQUEST,
  '__module__' : 'movie_recommendations_pb2'
  # @@protoc_insertion_point(class_scope:MovieRecommendationRequest)
  })
_sym_db.RegisterMessage(MovieRecommendationRequest)

MovieRecommendation = _reflection.GeneratedProtocolMessageType('MovieRecommendation', (_message.Message,), {
  'DESCRIPTOR' : _MOVIERECOMMENDATION,
  '__module__' : 'movie_recommendations_pb2'
  # @@protoc_insertion_point(class_scope:MovieRecommendation)
  })
_sym_db.RegisterMessage(MovieRecommendation)

MovieRecommendationResponse = _reflection.GeneratedProtocolMessageType('MovieRecommendationResponse', (_message.Message,), {
  'DESCRIPTOR' : _MOVIERECOMMENDATIONRESPONSE,
  '__module__' : 'movie_recommendations_pb2'
  # @@protoc_insertion_point(class_scope:MovieRecommendationResponse)
  })
_sym_db.RegisterMessage(MovieRecommendationResponse)

_RECOMMENDATIONS = DESCRIPTOR.services_by_name['Recommendations']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MOVIECATEGORY._serialized_start=261
  _MOVIECATEGORY._serialized_end=325
  _MOVIERECOMMENDATIONREQUEST._serialized_start=31
  _MOVIERECOMMENDATIONREQUEST._serialized_end=131
  _MOVIERECOMMENDATION._serialized_start=133
  _MOVIERECOMMENDATION._serialized_end=181
  _MOVIERECOMMENDATIONRESPONSE._serialized_start=183
  _MOVIERECOMMENDATIONRESPONSE._serialized_end=259
  _RECOMMENDATIONS._serialized_start=327
  _RECOMMENDATIONS._serialized_end=416
# @@protoc_insertion_point(module_scope)
